### ISSUE TITLE
Things I did for my formatted script & Suggestion

### ISSUE THREAD

**Issue by kpossibles** [RisingFog/InDesign-Scripts#2]
Find & Replace with Regex in Sublime Text to format script for Letterer Buddy

## convert SFX to uppercase

//FIND
`SFX:\h((\w+\h*)*)||SFX: (\w+\h+)`
//REPLACE
`\U\1`

//FIND
`SFX(\h*\(*(\w+\h*)+\)*): (\w+\h{0,1})`
//REPLACE
`SFX: \U\3`

## remove script identifiers & remove page numbers
//FIND
`Text: ||"": ||SFX: ||ST: ||<<>>: ||\[\]: ||([0-9]+)\.(\h*)\n`

## remove ` // ` from connected bubbles & add newline
//FIND
` // `
//REPLACE
`\n`

## Suggestion for removing Japanese characters
https://stackoverflow.com/questions/15033196/using-javascript-to-check-whether-a-string-contains-japanese-characters-includi

`/[\u3000-\u303f\u3040-\u309f\u30a0-\u30ff\uff00-\uff9f\u4e00-\u9faf\u3400-\u4dbf]/`

**Comment by RisingFog** [comment]
I've implemented all of these save for the SFX uppercase. Closing issue.
